title: Adnan Boxwala
subtitle: Software Development Engineer
description: >- # this means to ignore newlines until "baseurl:"
  Adnan Boxwala is a software development engineer by day, dreamer by night. Passionate about machine learning and it's application in autonomous driving.
url: "https://AdnanBox.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About 
      url: /about
    - text: Work Experience
      url : /experience
    - text: Education
      url : /education
    - text: Projects
      url : /projects
    - text: Professional Development
      url : /profdevelopment


# Edit these details

author_logo: profile.png
author: Adnan Boxwala
author_bio: As a Software Engineer in an agile team, I work towards transforming the software development
            and validation of highly automated driving functions from the real vehicle into the virtual world. While 
            continuously improving my programming skills in C++ and Python on the job, I fulfil my passion for 
            Artificial Intelligence by taking up online courses and reading articles in my personal time. 
author_email: "adnan93212@gmail.com"
author_location: Ingolstadt, Germany
author_location_url: "https://www.google.com/maps/place/Ingolstadt/@48.7534664,11.3096118,12z/data=!3m1!4b1!4m5!3m4!1s0x479efe5188360abb:0xec5d7e2213748aea!8m2!3d48.7665351!4d11.4257541"
typewrite-text: Looking for exciting opportunities to apply my knowledge of machine learning.

# Experiences
author_work_experiences:
            - company_name: Elektronische Fahrwerksysteme GmbH, Ingolstadt
              company_logo: efs.png
              company_url: https://www.efs-auto.com/
              alias_url: efs-auto.com
              designation: Software Development Engineer
              period: 01.01.2020 - present
              description:
                  - Development and setup of simulation systems for software development and validation 
                    of assisted and highly automated driving functions.
                  - Integration and commissioning of assisted and highly automated driving functions and 
                    connection of the simulation system via middleware.
                  - Requirement analysis and support of the users of the simulation system.
              visibility: true
            - company_name: dSPACE GmbH, Paderborn
              company_logo: dspace.png
              company_url: https://www.dspace.com/en/pub/home.cfm
              alias_url: dspace.com
              designation: Master Thesis Student
              certificate: dSPACE_MasterThesis.pdf
              period: 10.04.2019 - 09.09.2019
              description:
                  - Research and evaluation of different NN based algorithms object detection/segmentation using LiDAR data.
                  - Evaluate performance of the NN based algorithms on synthetic LiDAR data.
              visibility: true
            - company_name: dSPACE GmbH, Paderborn
              company_logo: dspace.png
              company_url: https://www.dspace.com/en/pub/home.cfm
              alias_url: dspace.com
              designation: Intern
              certificate: dSPACE.pdf
              period: 10.01.2019 - 09.04.2019
              description:
                  - Familiarised myself with the NVIDIA Drive AGX hardware platform to feed synthetic LiDAR data and 
                    evaluate performance of available functions.
                  - Creating virtual driving scenes in MotionDesk for generating a synthetic LiDAR dataset. 
                    Transform the data into a format fit for using with different neural networks.
              visibility: true
            - company_name: dSPACE GmbH, Paderborn
              company_logo: dspace.png
              company_url: https://www.dspace.com/en/pub/home.cfm
              alias_url: dspace.com
              designation: Working student
              certificate: dSPACE.pdf
              period: 01.10.2018 - 31.12.2018
              description:
                  - Induction to tools catering to ADAS/AD applications (RTMaps).
                  - Developed a component in RTMaps for labelling camera data obtained from SensorSim.
                  - Clustering/Segmentation of simulated LiDAR data.
              visibility: true
            - company_name: Fraunhofer IPA, Stuttgart
              company_logo: fraunhofer.png
              company_url: https://www.ipa.fraunhofer.de/
              alias_url: fraunhofer.de
              designation: Intern
              certificate: Fraunhofer.pdf
              period: 01.07.2018 - 30.09.2018
              description:
                  - Developed algorithms for mobile robots using ROS. Integrated features for obstacle detection using 
                    multiple ultrasonic sensors as well as monitoring the battery status.
                  - Carried out extensive research on determining suitability of Android Devices for implementing SLAM.
              visibility: true

# Education
author_education_details:
              - college_logo: FHAachen.png
                college_name: FH Aachen University of Applied Sciences
                period: 2016 - 2019
                college_url: https://www.fh-aachen.de/
                alias_url: fh-aachen.de
                college_degree: Mechatronics 
                description: Master of Science
                certificate: mastersDegree.pdf
                visibility: true
              - college_logo: sppu.png
                college_name: Savitribai Phule Pune University (formerly University of Pune)
                period: 2010 - 2014
                college_url: http://www.unipune.ac.in/
                alias_url: unipune.ac.in
                college_degree: Mechanical Engineering
                description: Bachelor of Engineering
                certificate: bachelorsDegree.pdf
                visibility: true
              - college_logo: dps.png
                college_name: Delhi Public School, Pune
                period: 2004 - 2010
                college_url: https://www.dpspune.com/
                alias_url: dpspune.com
                college_degree: High School
                description: Senior School Certificate Examination
                certificate: highSchool.pdf
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: routePlanning.png
                project_title: Route Planning (Udacity CPP Nanodegree)
                project_description: Implemented an A* search algorithm that plans a route between two points in 
                                     OpenStreetMap.
                project_url: https://github.com/AdnanBox/CppND-Route-Planning-Project
                alias_url: github.com/AdnanBox/CppND-Route-Planning-Project
                visibility: true
              - project_thumbnail: systemMonitor.png
                project_title: System Monitor (Udacity CPP Nanodegree)
                project_description: Wrote object-oriented C++ code to build a system monitor like the "htop" program
                                     in a linux system. 
                project_url: https://github.com/AdnanBox/CppND-System-Monitor
                alias_url: github.com/AdnanBox/CppND-System-Monitor
                visibility: true
              - project_thumbnail: memoryManagementChatbot.gif
                project_title: Memory Management Chatbot (Udacity CPP Nanodegree)
                project_description: Optimized a ChatBot program from a memory management perspective, by using smart 
                                     pointers and references.
                project_url: https://github.com/AdnanBox/CppND-Memory-Management-Chatbot
                alias_url: github.com/AdnanBox/CppND-Memory-Management-Chatbot
                visibility: true
              - project_thumbnail: concurrentTrafficSimulation.gif
                project_title: Concurrent Traffic Simulation (Udacity CPP Nanodegree)
                project_description: Built a thread-safe communication protocol between vehicles and traffic lights at 
                                     intersections using my knowledge of concurrent programming.
                project_url: https://github.com/AdnanBox/CppND-Program-a-Concurrent-Traffic-Simulation
                alias_url: github.com/AdnanBox/CppND-Program-a-Concurrent-Traffic-Simulation
                visibility: true
              - project_thumbnail: 2DfeatureTracking.png
                project_title: 2D Feature Tracking (Udacity Sensor Fusion Nanodegree)
                project_description: Extensively dealt with the OpenCV library to detect keypoints in camera images,
                                     extract and match descriptors.
                project_url: https://github.com/AdnanBox/SFND_2D_Feature_Tracking
                alias_url: github.com/AdnanBox/SFND_2D_Feature_Tracking
                visibility: true
              - project_thumbnail: 3DobjectTracking.png
                project_title: 3D Object Tracking (Udacity Sensor Fusion Nanodegree)
                project_description: Extended the code from the 2D Feature tracking project to match 3D objects over time
                                     and determine time to collision.
                project_url: https://github.com/AdnanBox/SFND_3D_Object_Tracking
                alias_url: github.com/AdnanBox/SFND_3D_Object_Tracking
                visibility: true
              - project_thumbnail: LiDARObstacleDetection.gif
                project_title: LiDAR Obstacle Detection (Udacity Sensor Fusion Nanodegree)
                project_description: Performed sensor fusion on LiDAR and RADAR sensor data to track multiple cars on the
                                     road, estimating their speed and position.
                project_url: https://github.com/AdnanBox/SFND_Lidar_Obstacle_Detection
                alias_url: github.com/AdnanBox/SFND_Lidar_Obstacle_Detection
                visibility: true
              - project_thumbnail: unscentedKalmanFilter.gif
                project_title: Unscented Kalman Filter (Udacity Sensor Fusion Nanodegree)
                project_description: Implemented an UKF to estimate the state of multiple cars on a highway using noisy 
                                     LiDAR and RADAR data measurements.
                project_url: https://github.com/AdnanBox/SFND_Unscented_Kalman_Filter
                alias_url: github.com/AdnanBox/SFND_Unscented_Kalman_Filter
                visibility: true

# Professional Development
author_professional_development:
              - course_name: Machine Learning
                platform: Coursera
                issue: Oct 2019
                certificate: machineLearning.pdf
                logo: coursera.png
                visibility: true
              - course_name: Deep Learning Specialization
                platform: deeplearning.ai on Coursera
                issue: Apr 2020
                certificate: DLSpecialization.pdf
                logo: deeplearningai.png
                visibility: true
              - course_name: Intro to TensorFlow for Artificial Intelligence, Machine Learning and Deep Learning
                platform: deeplearning.ai on Coursera
                issue: May 2020
                certificate: Intro2TF.pdf
                logo: deeplearningai.png
                visibility: true
              - course_name: Convolutional Neural Networks in TensorFlow
                platform: deeplearning.ai on Coursera
                issue: May 2020
                certificate: CNNTF.pdf
                logo: deeplearningai.png
                visibility: true
              - course_name: Sensor Fusion Nanodegree
                platform: Udacity
                issue: July 2020
                certificate: SensorFusion.pdf
                logo: udacity.png
                visibility: true
              - course_name: C++ Nanodegree
                platform: Udacity
                issue: ongoing*
                certificate: "./../../profdevelopment/"
                logo: udacity.png 
                visibility: true
              - course_name: Convolutional Neural Networks for Visual Recognition (CS231n)
                platform: Stanford University (MOOC, youtube)
                issue: ongoing*
                certificate: "./../../profdevelopment/"
                logo: stanford.png
                visibility: true
              

# social links
github_username:  AdnanBox
linkedin_username: adnan-boxwala
instagram_username: adnan_boxwala

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_prof_development: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build